name: .NET Tests & Coverage

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Test with coverage (runsettings)
        run: dotnet test --settings coverlet.runsettings --configuration Release

      - name: Generate coverage report (HTML)
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool || true
          reportgenerator -reports:"./**/TestResults/**/coverage.cobertura.xml" -targetdir:"./CoverageReport"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: CoverageReport
