name: Frontend Tests
on: [push, pull_request]

concurrency:
  group: fe-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clientapp
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: clientapp/package-lock.json
      - run: npm ci
      - run: npm run test:cov
        env: { CI: true }
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: clientapp/coverage
